#! /usr/bin/env python
import random

print('\033c')
print('The lunch location selected by this script is not negotiable:')
print('')

lunchList = [
             'County Line',
             'Sadie\'s',
             'Cervante\'s',
             'Leilani\'s Cafe',
             'K & I Diner (the full travis)',
             'Polittos con papas',
             'Thunderbird',
             'Red Rock Diner',
             'Giovanni\'s',
             'Dion\'s',
             'Jimmy John\'s',
             'Costco',
             'Griff\'s',
             'Tia Betty Blues',
             'Tia Betty Waffles',
             'Saggio\'s',
             'Bahn Mi Coda',
             'Cafe Trang',
             'Freddy\'s',
             'Thai Tip',
             'Vegan Thai',
             'Golden Pride',
             'Blake\'s', 
             'Bob\'s Burger',
             'Sonic',
             'The Tractor',
             'Lizard Tail',
             'La Salita',
             'Chic fil a',
             'Lynns House (call ahead)',
             'Powdrell\'s',
             'The Cube',
             'Frontier',
             'Two Fools',
             'Subway',
             'McDonald\'s (Kirtland)',
             'Burger King', 
             'Wendy\'s',
             'Carl\'s Jr',
             'Caesar\'s',
             'Hurricanes',
             'Taco Cabana',
             'Chili\'s',
             'Appleby\'s',
             'TGI Friday\'s',
             'B2B',
             'Cheese and Coffee',
             'Flying Star Cafe',
             'Weck\'s',
             'The Owl Cafe',
             'Rudys',
             'Cheesecake Factory',
             'Chipotle',
             'Taco Bell',
             'Del Taco',
             'Emissions testing place',
             'Basil Leaf',
             'Chen\'s',
             'Fantang',
             'Szechwan',
             'Slice Parlor',
             'Waffle House',
             'Relish',
             'Gino\'s New York Style',
             'Stufy\'s',
             'Cafe Istanbul (call to make sure their kitchen is open)',
             'Taj Palace'
             'Olive Garden',
             'High Finance',
             'Mall food court ()',
             'Uptown Sports Pub',
             'Panda Express',
             'Boston Market',
             'Los Cuates',
             'El patio',
             'Gardunos',
             'O Ramen',
             'Anapurna',
             'Sweet Tomatoes',
             'Super Salad',
             'Jason\'s Deli',
             'McCalister\'s',
             'Golden Corral',
             'UNM (the on in the dormitories)',
             'Scallo',
             'Tucano\'s',
             'Copper Lounge',
             'Kelly\'s',
             'Pizza Hut',
             'Domino\'s',
             'Godfather Pizza',
             'CiCi\'s Pizza',
             'Mongolian BBQ',
             'Lynn\'s Buffet',
             'IHOP',
             'Denny\'s',
             'Vick\'s Vittles',
             'Twister\'s',
             'Hooter\'s,',
             'Texas Roadhouse',
             'Texas Land and Cattle',
             'Santiago\'s',
             'Sandia Chille Grille',
             'Racetrack Casino',
             'Sandia Casino'
             'Whataburger',
             'Weinersnitzel',
             'Jack in the Box'
            ]
print(random.choice(lunchList))
print('')




